name: python3
channels:
  - conda-forge
dependencies:
  - python=3.6
  - anaconda=4.3
  - kwant=1.3
  - holoviews=1.7.0
  - xarray=0.9.1
  - hpc05  # This is only needed if you use a PBS cluster with headnode, as on the TU Delft network